#include "pulp.h"
#include "radix8_butterfly_driver.h"
#include "radix8_butterfly_regs.h" // The autogenerated reggen file [cite: 769]
#include <stdio.h>

// ---------------------------------------------------------
// Control & Status Functions
// ---------------------------------------------------------
void radix8_set_clk_en(uint8_t enable) {
    uint32_t volatile * ctrl_reg = (uint32_t*) (RADIX8_BUTTERFLY_BASE_ADDR + RADIX8_BUTTERFLY_CTRL_REG_OFFSET);
    uint32_t current_val = *ctrl_reg;
    
    if (enable) {
        *ctrl_reg = current_val | (1 << RADIX8_BUTTERFLY_CTRL_CLK_EN_BIT);
    } else {
        *ctrl_reg = current_val & ~(1 << RADIX8_BUTTERFLY_CTRL_CLK_EN_BIT);
    }
}

void radix8_clear_done(void) {
    uint32_t volatile * ctrl_reg = (uint32_t*) (RADIX8_BUTTERFLY_BASE_ADDR + RADIX8_BUTTERFLY_CTRL_REG_OFFSET);
    // Write 1 to clear bit, then write 0 to release it
    *ctrl_reg = (1 << RADIX8_BUTTERFLY_CTRL_CLEAR_BIT);
    *ctrl_reg = 0; 
}

void radix8_trigger_manual(void) {
    uint32_t volatile * ctrl_reg = (uint32_t*) (RADIX8_BUTTERFLY_BASE_ADDR + RADIX8_BUTTERFLY_CTRL_REG_OFFSET);
    *ctrl_reg = (1 << RADIX8_BUTTERFLY_CTRL_TRIGGER_BIT);
}

void radix8_poll_done(void) {
    uint32_t volatile * status_reg = (uint32_t*) (RADIX8_BUTTERFLY_BASE_ADDR + RADIX8_BUTTERFLY_STATUS_REG_OFFSET);
    
    // Spin-wait until the hardware asserts the DONE bit
    while (((*status_reg) & (1 << RADIX8_BUTTERFLY_STATUS_DONE_BIT)) == 0) {
        // Polling loop
    }
}

void radix8_set_twiddle(uint16_t twiddle_idx) {
    uint32_t volatile * twiddle_reg = (uint32_t*) (RADIX8_BUTTERFLY_BASE_ADDR + RADIX8_BUTTERFLY_TWIDDLE_REG_OFFSET);
    *twiddle_reg = twiddle_idx;
}

// ---------------------------------------------------------
// Data I/O Functions
// ---------------------------------------------------------
void radix8_write_operands(uint32_t* complex_data_in) {
    // Because DATA0 through DATA7 are mapped contiguously in the reg file,
    // we can use pointer arithmetic to write them in a loop[cite: 716].
    uint32_t volatile * data_reg_start = (uint32_t*) (RADIX8_BUTTERFLY_BASE_ADDR + RADIX8_BUTTERFLY_DATA0_REG_OFFSET);
    
    for (int i = 0; i < 8; i++) {
        data_reg_start[i] = complex_data_in[i];
    }
    // CRITICAL: Writing to index 7 (DATA7) automatically triggers the hardware 
    // because of the hwqe flag in your .hjson!
}

void radix8_read_results(uint32_t* complex_data_out) {
    uint32_t volatile * result_reg_start = (uint32_t*) (RADIX8_BUTTERFLY_BASE_ADDR + RADIX8_BUTTERFLY_OUT0_REG_OFFSET);
    
    for (int i = 0; i < 8; i++) {
        complex_data_out[i] = result_reg_start[i];
    }
}

// ---------------------------------------------------------
// High-Level Wrapper
// ---------------------------------------------------------
void radix8_compute(uint32_t* data_in, uint16_t twiddle_idx, uint32_t* data_out) {
    // 1. Ensure done flag is clean before starting
    radix8_clear_done();
    
    // 2. Set the configuration
    radix8_set_clk_en(1);
    radix8_set_twiddle(twiddle_idx);
    
    // 3. Write data (This automatically triggers execution on the last write)
    radix8_write_operands(data_in);
    
    // 4. Wait for the pipeline to finish (2 cycles + bus latency)
    radix8_poll_done();
    
    // 5. Retrieve the latched answers
    radix8_read_results(data_out);
}
