// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package butterfly_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 5;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } trigger;
    struct packed {
      logic        q;
      logic        qe;
    } clear;
  } butterfly_reg2hw_ctrl_reg_t;

  typedef struct packed {
    logic [10:0] q;
  } butterfly_reg2hw_twiddle_reg_t;

  typedef struct packed {
    logic [23:0] q;
  } butterfly_reg2hw_op_left_reg_t;

  typedef struct packed {
    logic [23:0] q;
  } butterfly_reg2hw_op_right_reg_t;

  typedef struct packed {
    logic        d;
  } butterfly_hw2reg_status_reg_t;

  typedef struct packed {
    logic [23:0] d;
  } butterfly_hw2reg_res_left_reg_t;

  typedef struct packed {
    logic [23:0] d;
  } butterfly_hw2reg_res_right_reg_t;

  // Register -> HW type
  typedef struct packed {
    butterfly_reg2hw_ctrl_reg_t ctrl; // [62:59]
    butterfly_reg2hw_twiddle_reg_t twiddle; // [58:48]
    butterfly_reg2hw_op_left_reg_t op_left; // [47:24]
    butterfly_reg2hw_op_right_reg_t op_right; // [23:0]
  } butterfly_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    butterfly_hw2reg_status_reg_t status; // [48:48]
    butterfly_hw2reg_res_left_reg_t res_left; // [47:24]
    butterfly_hw2reg_res_right_reg_t res_right; // [23:0]
  } butterfly_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] BUTTERFLY_CTRL_OFFSET = 5'h 0;
  parameter logic [BlockAw-1:0] BUTTERFLY_STATUS_OFFSET = 5'h 4;
  parameter logic [BlockAw-1:0] BUTTERFLY_TWIDDLE_OFFSET = 5'h 8;
  parameter logic [BlockAw-1:0] BUTTERFLY_OP_LEFT_OFFSET = 5'h c;
  parameter logic [BlockAw-1:0] BUTTERFLY_OP_RIGHT_OFFSET = 5'h 10;
  parameter logic [BlockAw-1:0] BUTTERFLY_RES_LEFT_OFFSET = 5'h 14;
  parameter logic [BlockAw-1:0] BUTTERFLY_RES_RIGHT_OFFSET = 5'h 18;

  // Reset values for hwext registers and their fields
  parameter logic [1:0] BUTTERFLY_CTRL_RESVAL = 2'h 0;
  parameter logic [0:0] BUTTERFLY_STATUS_RESVAL = 1'h 0;
  parameter logic [23:0] BUTTERFLY_RES_LEFT_RESVAL = 24'h 0;
  parameter logic [23:0] BUTTERFLY_RES_RIGHT_RESVAL = 24'h 0;

  // Register index
  typedef enum int {
    BUTTERFLY_CTRL,
    BUTTERFLY_STATUS,
    BUTTERFLY_TWIDDLE,
    BUTTERFLY_OP_LEFT,
    BUTTERFLY_OP_RIGHT,
    BUTTERFLY_RES_LEFT,
    BUTTERFLY_RES_RIGHT
  } butterfly_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] BUTTERFLY_PERMIT [7] = '{
    4'b 0001, // index[0] BUTTERFLY_CTRL
    4'b 0001, // index[1] BUTTERFLY_STATUS
    4'b 0011, // index[2] BUTTERFLY_TWIDDLE
    4'b 0111, // index[3] BUTTERFLY_OP_LEFT
    4'b 0111, // index[4] BUTTERFLY_OP_RIGHT
    4'b 0111, // index[5] BUTTERFLY_RES_LEFT
    4'b 0111  // index[6] BUTTERFLY_RES_RIGHT
  };

endpackage

