
`include "register_interface/typedef.svh"

module butterfly_tcdm_top #(
    parameter int unsigned ADDR_WIDTH = 32,
    parameter int unsigned DATA_WIDTH = 32
) (
    input  logic                    clk_i,
    input  logic                    rst_ni, 
    input  logic                    test_mode_i,

    // NEW: Use the standard PULP TCDM Interface instead of raw wires!
    XBAR_TCDM_BUS.Slave             tcdm_slave
);

    import butterfly_reg_pkg::butterfly_reg2hw_t;
    import butterfly_reg_pkg::butterfly_hw2reg_t;

    // 1. Struct Definitions for Generic Register Interface
    typedef logic [ADDR_WIDTH-1:0]   addr_t;
    typedef logic [DATA_WIDTH-1:0]   data_t;
    typedef logic [DATA_WIDTH/8-1:0] strb_t;

    `REG_BUS_TYPEDEF_REQ(reg_req_t, addr_t, data_t, strb_t)
    `REG_BUS_TYPEDEF_RSP(reg_rsp_t, data_t)

    reg_req_t reg_req;
    reg_rsp_t reg_rsp;

    butterfly_reg2hw_t reg2hw;
    butterfly_hw2reg_t hw2reg;

    // 2. Direct Protocol Conversion: tcdm_slave -> reg_req_t
    assign reg_req.valid = tcdm_slave.req;
    assign reg_req.write = ~tcdm_slave.wen; // Invert to active-high write
    assign reg_req.addr  = tcdm_slave.add;
    assign reg_req.wdata = tcdm_slave.wdata;
    assign reg_req.wstrb = tcdm_slave.be;

    assign tcdm_slave.gnt = reg_rsp.ready;

    // 3. TCDM Read Response Pipeline (1-cycle delay required by TCDM)
    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            tcdm_slave.r_valid <= 1'b0;
            tcdm_slave.r_rdata <= '0;
        end else begin
            // If request is valid, granted, and it's a read (wen=1), data is valid next cycle
            tcdm_slave.r_valid <= tcdm_slave.req && tcdm_slave.gnt && tcdm_slave.wen; 
            tcdm_slave.r_rdata <= reg_rsp.rdata;
        end
    end

    // 4. Instantiating the Autogenerated Register File
    butterfly_reg_top #(
        .reg_req_t(reg_req_t),
        .reg_rsp_t(reg_rsp_t)
    ) i_regfile (
        .clk_i      (clk_i),
        .rst_ni     (rst_ni),
        .devmode_i  (1'b1),
        .reg_req_i  (reg_req),
        .reg_rsp_o  (reg_rsp),
        .reg2hw     (reg2hw),
        .hw2reg     (hw2reg)
    );

    // 5. Hardware Interface Signals
    logic        bfly_trigger;
    logic        bfly_done_pulse;
    logic [23:0] bfly_o_left;
    logic [23:0] bfly_o_right;

    assign bfly_trigger = reg2hw.ctrl.trigger.q & reg2hw.ctrl.trigger.qe;

    // 6. Instantiating the Butterfly Math Core
    simple_butterfly #(
        .IWIDTH(12), 
        .CWIDTH(16), 
        .OWIDTH(12), 
        .SHIFT(0)
    ) i_butterfly (
        .i_clk         (clk_i),
        .i_reset       (~rst_ni),
        .i_clk_enable  (1'b1),
        
        // REMOVED .idx and .data from these three lines:
        .i_twiddle_idx (reg2hw.twiddle.q),
        .i_left        (reg2hw.op_left.q),
        .i_right       (reg2hw.op_right.q),
        
        .i_aux         (bfly_trigger),
        .o_left        (bfly_o_left),
        .o_right       (bfly_o_right),
        .o_aux         (bfly_done_pulse)
    );

 

// 7. Data Latching Logic (Critical for DMA Polling)
    logic        done_flag_q;
    logic [23:0] res_left_q;
    logic [23:0] res_right_q;

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            done_flag_q <= 1'b0;
            res_left_q  <= '0;
            res_right_q <= '0;
        end else begin
            // Clear flag when software writes to CTRL.CLEAR
            if (reg2hw.ctrl.clear.qe && reg2hw.ctrl.clear.q) begin
                done_flag_q <= 1'b0;
            end 
            // Set flag and latch data when butterfly finishes
            else if (bfly_done_pulse) begin
                done_flag_q <= 1'b1;
                res_left_q  <= bfly_o_left;
                res_right_q <= bfly_o_right;
            end
        end // <--- MAKE SURE THIS 'end' IS HERE
    end     // <--- MAKE SURE THIS 'end' IS HERE

    // Wire latched data back to the register file (REMOVED .done and .data)
    assign hw2reg.status.d    = done_flag_q;
    assign hw2reg.res_left.d  = res_left_q;
    assign hw2reg.res_right.d = res_right_q;
    
    // =========================================================================
    // 8. HARDWARE DIAGNOSTIC PRINTS (Simulation Only)
    // =========================================================================
    // pragma translate_off
    always @(posedge clk_i) begin
        // Print when the software writes to the TRIGGER bit in the CTRL register
        if (bfly_trigger) begin
            $display("[HW DEBUG] CYCLE %0t: Trigger received! bfly_trigger is HIGH", $time);
            $fflush(); // Force Questasim to print immediately
        end
            
        // Print when the math core asserts the done pulse
        if (bfly_done_pulse) begin
            $display("[HW DEBUG] CYCLE %0t: Pipeline Finished! bfly_done_pulse is HIGH", $time);
            $fflush(); // Force Questasim to print immediately
        end
    end
    // pragma translate_on

endmodule
