`include "register_interface/typedef.svh"

module radix8_butterfly_tcdm_top #(
    parameter int unsigned ADDR_WIDTH = 32,
    parameter int unsigned DATA_WIDTH = 32
) (
    input  logic                    clk_i,
    input  logic                    rst_ni, 
    input  logic                    test_mode_i,

    // Standard PULP TCDM Interface
    XBAR_TCDM_BUS.Slave             tcdm_slave
);

    import radix8_butterfly_reg_pkg::radix8_butterfly_reg2hw_t;
    import radix8_butterfly_reg_pkg::radix8_butterfly_hw2reg_t;

    // =========================================================================
    // 1. Struct Definitions for Generic Register Interface
    // =========================================================================
    typedef logic [ADDR_WIDTH-1:0]   addr_t;
    typedef logic [DATA_WIDTH-1:0]   data_t;
    typedef logic [DATA_WIDTH/8-1:0] strb_t;

    // Generate the request and response structs used by the reg_top module
    `REG_BUS_TYPEDEF_REQ(reg_req_t, addr_t, data_t, strb_t)
    `REG_BUS_TYPEDEF_RSP(reg_rsp_t, data_t)

    reg_req_t reg_req;
    reg_rsp_t reg_rsp;

    radix8_butterfly_reg2hw_t reg2hw;
    radix8_butterfly_hw2reg_t hw2reg;


    // =========================================================================
    // 2. Direct Protocol Conversion: tcdm_slave -> reg_req_t
    // =========================================================================
    // Map the TCDM bus signals into the register interface struct format
    assign reg_req.valid = tcdm_slave.req;
    assign reg_req.write = ~tcdm_slave.wen; // TCDM wen is active-low for writes, reg_req is active-high
    assign reg_req.addr  = tcdm_slave.add;
    assign reg_req.wdata = tcdm_slave.wdata;
    assign reg_req.wstrb = tcdm_slave.be;

    assign tcdm_slave.gnt = reg_rsp.ready;


    // =========================================================================
    // 3. TCDM Read Response Pipeline 
    // =========================================================================
    // TCDM interconnects strictly expect read valid/data one cycle after the grant
    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            tcdm_slave.r_valid <= 1'b0;
            tcdm_slave.r_rdata <= '0;
        end else begin
            // If request is valid, granted, and it's a read (wen=1), data is valid next cycle
            tcdm_slave.r_valid <= tcdm_slave.req && tcdm_slave.gnt && tcdm_slave.wen; 
            tcdm_slave.r_rdata <= reg_rsp.rdata;
        end
    end


    // =========================================================================
    // 4. Instantiating the Autogenerated Register File
    // =========================================================================
    radix8_butterfly_reg_top #(
        .reg_req_t(reg_req_t),
        .reg_rsp_t(reg_rsp_t)
    ) i_regfile (
        .clk_i      (clk_i),
        .rst_ni     (rst_ni),
        .devmode_i  (1'b1),
        .reg_req_i  (reg_req),
        .reg_rsp_o  (reg_rsp),
        .reg2hw     (reg2hw),
        .hw2reg     (hw2reg)
    );


    // =========================================================================
    // 5. Hardware Interface Signals & Auto-Trigger
    // =========================================================================
    logic        bfly_trigger;
    logic        bfly_done_pulse;
    
    // Arrays for cleaner signal mapping to/from the core
    logic [31:0] bfly_o_data [8];

    // Auto-Trigger when the CPU writes to the final input register (DATA7)
    // qe (Write Enable) pulses high for 1 cycle during the transaction.
    assign bfly_trigger = reg2hw.data7.qe;


    // =========================================================================
    // 6. Instantiating the Radix-8 Butterfly Core
    // =========================================================================
    radix8_butterfly_verbose #(
        .IWIDTH(16), 
        .CWIDTH(16), 
        .OWIDTH(16), 
        .SHIFT(0)
    ) i_butterfly (
        .i_clk         (clk_i),
        .i_reset       (~rst_ni),             // Assuming your core uses active-high reset
        .i_clk_enable  (1'b1),                // Hardwired to 1 matching your reference
        
        // Single field registers flatten in struct, so we use .q directly
        .i_twiddle_idx (reg2hw.twiddle.q[8:0]), 
        
        .i_data0       (reg2hw.data0.q),
        .i_data1       (reg2hw.data1.q),
        .i_data2       (reg2hw.data2.q),
        .i_data3       (reg2hw.data3.q),
        .i_data4       (reg2hw.data4.q),
        .i_data5       (reg2hw.data5.q),
        .i_data6       (reg2hw.data6.q),
        .i_data7       (reg2hw.data7.q),
        
        .i_aux         (bfly_trigger),

        .o_data0       (bfly_o_data[0]),
        .o_data1       (bfly_o_data[1]),
        .o_data2       (bfly_o_data[2]),
        .o_data3       (bfly_o_data[3]),
        .o_data4       (bfly_o_data[4]),
        .o_data5       (bfly_o_data[5]),
        .o_data6       (bfly_o_data[6]),
        .o_data7       (bfly_o_data[7]),
        
        .o_aux         (bfly_done_pulse)
    );


    // =========================================================================
    // 7. Zero-Latency Data Latching Logic (Critical for DMA Polling)
    // =========================================================================
    logic        done_flag_q;
    logic [31:0] res_data_q [8];

    always_ff @(posedge clk_i or negedge rst_ni) begin
        if (!rst_ni) begin
            done_flag_q <= 1'b0;
            for (int i=0; i<8; i++) begin
                res_data_q[i] <= '0;
            end
        end else begin
            // Auto-clear the flag if the CPU manually requests a clear OR if a new trigger fires
            if ((reg2hw.ctrl.clear.qe && reg2hw.ctrl.clear.q) || bfly_trigger) begin
                done_flag_q <= 1'b0;
            end 
            // Set flag and latch data on the exact cycle the butterfly finishes. 
            // Since the core takes 2 cycles, this flip-flop stores it on cycle 3, adding 0 latency to SW reads.
            else if (bfly_done_pulse) begin
                done_flag_q   <= 1'b1;
                res_data_q[0] <= bfly_o_data[0];
                res_data_q[1] <= bfly_o_data[1];
                res_data_q[2] <= bfly_o_data[2];
                res_data_q[3] <= bfly_o_data[3];
                res_data_q[4] <= bfly_o_data[4];
                res_data_q[5] <= bfly_o_data[5];
                res_data_q[6] <= bfly_o_data[6];
                res_data_q[7] <= bfly_o_data[7];
            end
        end
    end

    // Wire latched data back to the register file (Flattened format)
    assign hw2reg.status.d = done_flag_q;
    assign hw2reg.out0.d   = res_data_q[0];
    assign hw2reg.out1.d   = res_data_q[1];
    assign hw2reg.out2.d   = res_data_q[2];
    assign hw2reg.out3.d   = res_data_q[3];
    assign hw2reg.out4.d   = res_data_q[4];
    assign hw2reg.out5.d   = res_data_q[5];
    assign hw2reg.out6.d   = res_data_q[6];
    assign hw2reg.out7.d   = res_data_q[7];
    

    // =========================================================================
    // 8. HARDWARE DIAGNOSTIC PRINTS (Simulation Only)
    // =========================================================================
    // pragma translate_off
    always @(posedge clk_i) begin
        // Print when the software triggers via DATA7 write
        if (bfly_trigger) begin
            $display("[HW DEBUG] CYCLE %0t: Trigger received! Radix-8 Butterfly starting...", $time);
            $fflush(); // Force Questasim to print immediately
        end
            
        // Print when the math core asserts the done pulse
        if (bfly_done_pulse) begin
            $display("[HW DEBUG] CYCLE %0t: Pipeline Finished! Radix-8 Outputs latched.", $time);
            $fflush(); // Force Questasim to print immediately
        end
    end
    // pragma translate_on

endmodule
