// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package radix8_butterfly_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 7;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    struct packed {
      logic        q;
      logic        qe;
    } trigger;
    struct packed {
      logic        q;
      logic        qe;
    } clear;
    struct packed {
      logic        q;
      logic        qe;
    } clk_en;
  } radix8_butterfly_reg2hw_ctrl_reg_t;

  typedef struct packed {
    logic [8:0]  q;
  } radix8_butterfly_reg2hw_twiddle_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } radix8_butterfly_reg2hw_data0_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } radix8_butterfly_reg2hw_data1_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } radix8_butterfly_reg2hw_data2_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } radix8_butterfly_reg2hw_data3_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } radix8_butterfly_reg2hw_data4_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } radix8_butterfly_reg2hw_data5_reg_t;

  typedef struct packed {
    logic [31:0] q;
  } radix8_butterfly_reg2hw_data6_reg_t;

  typedef struct packed {
    logic [31:0] q;
    logic        qe;
  } radix8_butterfly_reg2hw_data7_reg_t;

  typedef struct packed {
    logic        d;
  } radix8_butterfly_hw2reg_status_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } radix8_butterfly_hw2reg_out0_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } radix8_butterfly_hw2reg_out1_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } radix8_butterfly_hw2reg_out2_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } radix8_butterfly_hw2reg_out3_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } radix8_butterfly_hw2reg_out4_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } radix8_butterfly_hw2reg_out5_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } radix8_butterfly_hw2reg_out6_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } radix8_butterfly_hw2reg_out7_reg_t;

  // Register -> HW type
  typedef struct packed {
    radix8_butterfly_reg2hw_ctrl_reg_t ctrl; // [271:266]
    radix8_butterfly_reg2hw_twiddle_reg_t twiddle; // [265:257]
    radix8_butterfly_reg2hw_data0_reg_t data0; // [256:225]
    radix8_butterfly_reg2hw_data1_reg_t data1; // [224:193]
    radix8_butterfly_reg2hw_data2_reg_t data2; // [192:161]
    radix8_butterfly_reg2hw_data3_reg_t data3; // [160:129]
    radix8_butterfly_reg2hw_data4_reg_t data4; // [128:97]
    radix8_butterfly_reg2hw_data5_reg_t data5; // [96:65]
    radix8_butterfly_reg2hw_data6_reg_t data6; // [64:33]
    radix8_butterfly_reg2hw_data7_reg_t data7; // [32:0]
  } radix8_butterfly_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    radix8_butterfly_hw2reg_status_reg_t status; // [256:256]
    radix8_butterfly_hw2reg_out0_reg_t out0; // [255:224]
    radix8_butterfly_hw2reg_out1_reg_t out1; // [223:192]
    radix8_butterfly_hw2reg_out2_reg_t out2; // [191:160]
    radix8_butterfly_hw2reg_out3_reg_t out3; // [159:128]
    radix8_butterfly_hw2reg_out4_reg_t out4; // [127:96]
    radix8_butterfly_hw2reg_out5_reg_t out5; // [95:64]
    radix8_butterfly_hw2reg_out6_reg_t out6; // [63:32]
    radix8_butterfly_hw2reg_out7_reg_t out7; // [31:0]
  } radix8_butterfly_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_CTRL_OFFSET = 7'h 0;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_STATUS_OFFSET = 7'h 4;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_TWIDDLE_OFFSET = 7'h 8;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_DATA0_OFFSET = 7'h c;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_DATA1_OFFSET = 7'h 10;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_DATA2_OFFSET = 7'h 14;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_DATA3_OFFSET = 7'h 18;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_DATA4_OFFSET = 7'h 1c;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_DATA5_OFFSET = 7'h 20;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_DATA6_OFFSET = 7'h 24;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_DATA7_OFFSET = 7'h 28;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_OUT0_OFFSET = 7'h 2c;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_OUT1_OFFSET = 7'h 30;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_OUT2_OFFSET = 7'h 34;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_OUT3_OFFSET = 7'h 38;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_OUT4_OFFSET = 7'h 3c;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_OUT5_OFFSET = 7'h 40;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_OUT6_OFFSET = 7'h 44;
  parameter logic [BlockAw-1:0] RADIX8_BUTTERFLY_OUT7_OFFSET = 7'h 48;

  // Reset values for hwext registers and their fields
  parameter logic [0:0] RADIX8_BUTTERFLY_STATUS_RESVAL = 1'h 0;
  parameter logic [31:0] RADIX8_BUTTERFLY_OUT0_RESVAL = 32'h 0;
  parameter logic [31:0] RADIX8_BUTTERFLY_OUT1_RESVAL = 32'h 0;
  parameter logic [31:0] RADIX8_BUTTERFLY_OUT2_RESVAL = 32'h 0;
  parameter logic [31:0] RADIX8_BUTTERFLY_OUT3_RESVAL = 32'h 0;
  parameter logic [31:0] RADIX8_BUTTERFLY_OUT4_RESVAL = 32'h 0;
  parameter logic [31:0] RADIX8_BUTTERFLY_OUT5_RESVAL = 32'h 0;
  parameter logic [31:0] RADIX8_BUTTERFLY_OUT6_RESVAL = 32'h 0;
  parameter logic [31:0] RADIX8_BUTTERFLY_OUT7_RESVAL = 32'h 0;

  // Register index
  typedef enum int {
    RADIX8_BUTTERFLY_CTRL,
    RADIX8_BUTTERFLY_STATUS,
    RADIX8_BUTTERFLY_TWIDDLE,
    RADIX8_BUTTERFLY_DATA0,
    RADIX8_BUTTERFLY_DATA1,
    RADIX8_BUTTERFLY_DATA2,
    RADIX8_BUTTERFLY_DATA3,
    RADIX8_BUTTERFLY_DATA4,
    RADIX8_BUTTERFLY_DATA5,
    RADIX8_BUTTERFLY_DATA6,
    RADIX8_BUTTERFLY_DATA7,
    RADIX8_BUTTERFLY_OUT0,
    RADIX8_BUTTERFLY_OUT1,
    RADIX8_BUTTERFLY_OUT2,
    RADIX8_BUTTERFLY_OUT3,
    RADIX8_BUTTERFLY_OUT4,
    RADIX8_BUTTERFLY_OUT5,
    RADIX8_BUTTERFLY_OUT6,
    RADIX8_BUTTERFLY_OUT7
  } radix8_butterfly_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] RADIX8_BUTTERFLY_PERMIT [19] = '{
    4'b 0001, // index[ 0] RADIX8_BUTTERFLY_CTRL
    4'b 0001, // index[ 1] RADIX8_BUTTERFLY_STATUS
    4'b 0011, // index[ 2] RADIX8_BUTTERFLY_TWIDDLE
    4'b 1111, // index[ 3] RADIX8_BUTTERFLY_DATA0
    4'b 1111, // index[ 4] RADIX8_BUTTERFLY_DATA1
    4'b 1111, // index[ 5] RADIX8_BUTTERFLY_DATA2
    4'b 1111, // index[ 6] RADIX8_BUTTERFLY_DATA3
    4'b 1111, // index[ 7] RADIX8_BUTTERFLY_DATA4
    4'b 1111, // index[ 8] RADIX8_BUTTERFLY_DATA5
    4'b 1111, // index[ 9] RADIX8_BUTTERFLY_DATA6
    4'b 1111, // index[10] RADIX8_BUTTERFLY_DATA7
    4'b 1111, // index[11] RADIX8_BUTTERFLY_OUT0
    4'b 1111, // index[12] RADIX8_BUTTERFLY_OUT1
    4'b 1111, // index[13] RADIX8_BUTTERFLY_OUT2
    4'b 1111, // index[14] RADIX8_BUTTERFLY_OUT3
    4'b 1111, // index[15] RADIX8_BUTTERFLY_OUT4
    4'b 1111, // index[16] RADIX8_BUTTERFLY_OUT5
    4'b 1111, // index[17] RADIX8_BUTTERFLY_OUT6
    4'b 1111  // index[18] RADIX8_BUTTERFLY_OUT7
  };

endpackage

