// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module radix8_butterfly_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 7
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output radix8_butterfly_reg_pkg::radix8_butterfly_reg2hw_t reg2hw, // Write
  input  radix8_butterfly_reg_pkg::radix8_butterfly_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import radix8_butterfly_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic ctrl_trigger_qs;
  logic ctrl_trigger_wd;
  logic ctrl_trigger_we;
  logic ctrl_clear_qs;
  logic ctrl_clear_wd;
  logic ctrl_clear_we;
  logic ctrl_clk_en_qs;
  logic ctrl_clk_en_wd;
  logic ctrl_clk_en_we;
  logic status_qs;
  logic status_re;
  logic [8:0] twiddle_qs;
  logic [8:0] twiddle_wd;
  logic twiddle_we;
  logic [31:0] data0_qs;
  logic [31:0] data0_wd;
  logic data0_we;
  logic [31:0] data1_qs;
  logic [31:0] data1_wd;
  logic data1_we;
  logic [31:0] data2_qs;
  logic [31:0] data2_wd;
  logic data2_we;
  logic [31:0] data3_qs;
  logic [31:0] data3_wd;
  logic data3_we;
  logic [31:0] data4_qs;
  logic [31:0] data4_wd;
  logic data4_we;
  logic [31:0] data5_qs;
  logic [31:0] data5_wd;
  logic data5_we;
  logic [31:0] data6_qs;
  logic [31:0] data6_wd;
  logic data6_we;
  logic [31:0] data7_qs;
  logic [31:0] data7_wd;
  logic data7_we;
  logic [31:0] out0_qs;
  logic out0_re;
  logic [31:0] out1_qs;
  logic out1_re;
  logic [31:0] out2_qs;
  logic out2_re;
  logic [31:0] out3_qs;
  logic out3_re;
  logic [31:0] out4_qs;
  logic out4_re;
  logic [31:0] out5_qs;
  logic out5_re;
  logic [31:0] out6_qs;
  logic out6_re;
  logic [31:0] out7_qs;
  logic out7_re;

  // Register instances
  // R[ctrl]: V(False)

  //   F[trigger]: 0:0
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_ctrl_trigger (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_trigger_we),
    .wd     (ctrl_trigger_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (reg2hw.ctrl.trigger.qe),
    .q      (reg2hw.ctrl.trigger.q ),

    // to register interface (read)
    .qs     (ctrl_trigger_qs)
  );


  //   F[clear]: 1:1
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_ctrl_clear (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_clear_we),
    .wd     (ctrl_clear_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (reg2hw.ctrl.clear.qe),
    .q      (reg2hw.ctrl.clear.q ),

    // to register interface (read)
    .qs     (ctrl_clear_qs)
  );


  //   F[clk_en]: 2:2
  prim_subreg #(
    .DW      (1),
    .SWACCESS("RW"),
    .RESVAL  (1'h0)
  ) u_ctrl_clk_en (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (ctrl_clk_en_we),
    .wd     (ctrl_clk_en_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (reg2hw.ctrl.clk_en.qe),
    .q      (reg2hw.ctrl.clk_en.q ),

    // to register interface (read)
    .qs     (ctrl_clk_en_qs)
  );


  // R[status]: V(True)

  prim_subreg_ext #(
    .DW    (1)
  ) u_status (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (status_qs)
  );


  // R[twiddle]: V(False)

  prim_subreg #(
    .DW      (9),
    .SWACCESS("RW"),
    .RESVAL  (9'h0)
  ) u_twiddle (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (twiddle_we),
    .wd     (twiddle_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.twiddle.q ),

    // to register interface (read)
    .qs     (twiddle_qs)
  );


  // R[data0]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_data0 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (data0_we),
    .wd     (data0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data0.q ),

    // to register interface (read)
    .qs     (data0_qs)
  );


  // R[data1]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_data1 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (data1_we),
    .wd     (data1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data1.q ),

    // to register interface (read)
    .qs     (data1_qs)
  );


  // R[data2]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_data2 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (data2_we),
    .wd     (data2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data2.q ),

    // to register interface (read)
    .qs     (data2_qs)
  );


  // R[data3]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_data3 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (data3_we),
    .wd     (data3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data3.q ),

    // to register interface (read)
    .qs     (data3_qs)
  );


  // R[data4]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_data4 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (data4_we),
    .wd     (data4_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data4.q ),

    // to register interface (read)
    .qs     (data4_qs)
  );


  // R[data5]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_data5 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (data5_we),
    .wd     (data5_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data5.q ),

    // to register interface (read)
    .qs     (data5_qs)
  );


  // R[data6]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_data6 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (data6_we),
    .wd     (data6_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.data6.q ),

    // to register interface (read)
    .qs     (data6_qs)
  );


  // R[data7]: V(False)

  prim_subreg #(
    .DW      (32),
    .SWACCESS("RW"),
    .RESVAL  (32'h0)
  ) u_data7 (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (data7_we),
    .wd     (data7_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (reg2hw.data7.qe),
    .q      (reg2hw.data7.q ),

    // to register interface (read)
    .qs     (data7_qs)
  );


  // R[out0]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_out0 (
    .re     (out0_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.out0.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (out0_qs)
  );


  // R[out1]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_out1 (
    .re     (out1_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.out1.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (out1_qs)
  );


  // R[out2]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_out2 (
    .re     (out2_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.out2.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (out2_qs)
  );


  // R[out3]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_out3 (
    .re     (out3_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.out3.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (out3_qs)
  );


  // R[out4]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_out4 (
    .re     (out4_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.out4.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (out4_qs)
  );


  // R[out5]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_out5 (
    .re     (out5_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.out5.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (out5_qs)
  );


  // R[out6]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_out6 (
    .re     (out6_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.out6.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (out6_qs)
  );


  // R[out7]: V(True)

  prim_subreg_ext #(
    .DW    (32)
  ) u_out7 (
    .re     (out7_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.out7.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (out7_qs)
  );




  logic [18:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[ 0] = (reg_addr == RADIX8_BUTTERFLY_CTRL_OFFSET);
    addr_hit[ 1] = (reg_addr == RADIX8_BUTTERFLY_STATUS_OFFSET);
    addr_hit[ 2] = (reg_addr == RADIX8_BUTTERFLY_TWIDDLE_OFFSET);
    addr_hit[ 3] = (reg_addr == RADIX8_BUTTERFLY_DATA0_OFFSET);
    addr_hit[ 4] = (reg_addr == RADIX8_BUTTERFLY_DATA1_OFFSET);
    addr_hit[ 5] = (reg_addr == RADIX8_BUTTERFLY_DATA2_OFFSET);
    addr_hit[ 6] = (reg_addr == RADIX8_BUTTERFLY_DATA3_OFFSET);
    addr_hit[ 7] = (reg_addr == RADIX8_BUTTERFLY_DATA4_OFFSET);
    addr_hit[ 8] = (reg_addr == RADIX8_BUTTERFLY_DATA5_OFFSET);
    addr_hit[ 9] = (reg_addr == RADIX8_BUTTERFLY_DATA6_OFFSET);
    addr_hit[10] = (reg_addr == RADIX8_BUTTERFLY_DATA7_OFFSET);
    addr_hit[11] = (reg_addr == RADIX8_BUTTERFLY_OUT0_OFFSET);
    addr_hit[12] = (reg_addr == RADIX8_BUTTERFLY_OUT1_OFFSET);
    addr_hit[13] = (reg_addr == RADIX8_BUTTERFLY_OUT2_OFFSET);
    addr_hit[14] = (reg_addr == RADIX8_BUTTERFLY_OUT3_OFFSET);
    addr_hit[15] = (reg_addr == RADIX8_BUTTERFLY_OUT4_OFFSET);
    addr_hit[16] = (reg_addr == RADIX8_BUTTERFLY_OUT5_OFFSET);
    addr_hit[17] = (reg_addr == RADIX8_BUTTERFLY_OUT6_OFFSET);
    addr_hit[18] = (reg_addr == RADIX8_BUTTERFLY_OUT7_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(RADIX8_BUTTERFLY_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(RADIX8_BUTTERFLY_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(RADIX8_BUTTERFLY_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(RADIX8_BUTTERFLY_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(RADIX8_BUTTERFLY_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(RADIX8_BUTTERFLY_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(RADIX8_BUTTERFLY_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(RADIX8_BUTTERFLY_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(RADIX8_BUTTERFLY_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(RADIX8_BUTTERFLY_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(RADIX8_BUTTERFLY_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(RADIX8_BUTTERFLY_PERMIT[11] & ~reg_be))) |
               (addr_hit[12] & (|(RADIX8_BUTTERFLY_PERMIT[12] & ~reg_be))) |
               (addr_hit[13] & (|(RADIX8_BUTTERFLY_PERMIT[13] & ~reg_be))) |
               (addr_hit[14] & (|(RADIX8_BUTTERFLY_PERMIT[14] & ~reg_be))) |
               (addr_hit[15] & (|(RADIX8_BUTTERFLY_PERMIT[15] & ~reg_be))) |
               (addr_hit[16] & (|(RADIX8_BUTTERFLY_PERMIT[16] & ~reg_be))) |
               (addr_hit[17] & (|(RADIX8_BUTTERFLY_PERMIT[17] & ~reg_be))) |
               (addr_hit[18] & (|(RADIX8_BUTTERFLY_PERMIT[18] & ~reg_be)))));
  end

  assign ctrl_trigger_we = addr_hit[0] & reg_we & !reg_error;
  assign ctrl_trigger_wd = reg_wdata[0];

  assign ctrl_clear_we = addr_hit[0] & reg_we & !reg_error;
  assign ctrl_clear_wd = reg_wdata[1];

  assign ctrl_clk_en_we = addr_hit[0] & reg_we & !reg_error;
  assign ctrl_clk_en_wd = reg_wdata[2];

  assign status_re = addr_hit[1] & reg_re & !reg_error;

  assign twiddle_we = addr_hit[2] & reg_we & !reg_error;
  assign twiddle_wd = reg_wdata[8:0];

  assign data0_we = addr_hit[3] & reg_we & !reg_error;
  assign data0_wd = reg_wdata[31:0];

  assign data1_we = addr_hit[4] & reg_we & !reg_error;
  assign data1_wd = reg_wdata[31:0];

  assign data2_we = addr_hit[5] & reg_we & !reg_error;
  assign data2_wd = reg_wdata[31:0];

  assign data3_we = addr_hit[6] & reg_we & !reg_error;
  assign data3_wd = reg_wdata[31:0];

  assign data4_we = addr_hit[7] & reg_we & !reg_error;
  assign data4_wd = reg_wdata[31:0];

  assign data5_we = addr_hit[8] & reg_we & !reg_error;
  assign data5_wd = reg_wdata[31:0];

  assign data6_we = addr_hit[9] & reg_we & !reg_error;
  assign data6_wd = reg_wdata[31:0];

  assign data7_we = addr_hit[10] & reg_we & !reg_error;
  assign data7_wd = reg_wdata[31:0];

  assign out0_re = addr_hit[11] & reg_re & !reg_error;

  assign out1_re = addr_hit[12] & reg_re & !reg_error;

  assign out2_re = addr_hit[13] & reg_re & !reg_error;

  assign out3_re = addr_hit[14] & reg_re & !reg_error;

  assign out4_re = addr_hit[15] & reg_re & !reg_error;

  assign out5_re = addr_hit[16] & reg_re & !reg_error;

  assign out6_re = addr_hit[17] & reg_re & !reg_error;

  assign out7_re = addr_hit[18] & reg_re & !reg_error;

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = ctrl_trigger_qs;
        reg_rdata_next[1] = ctrl_clear_qs;
        reg_rdata_next[2] = ctrl_clk_en_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = status_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[8:0] = twiddle_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = data0_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = data1_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = data2_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[31:0] = data3_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[31:0] = data4_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[31:0] = data5_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[31:0] = data6_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[31:0] = data7_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[31:0] = out0_qs;
      end

      addr_hit[12]: begin
        reg_rdata_next[31:0] = out1_qs;
      end

      addr_hit[13]: begin
        reg_rdata_next[31:0] = out2_qs;
      end

      addr_hit[14]: begin
        reg_rdata_next[31:0] = out3_qs;
      end

      addr_hit[15]: begin
        reg_rdata_next[31:0] = out4_qs;
      end

      addr_hit[16]: begin
        reg_rdata_next[31:0] = out5_qs;
      end

      addr_hit[17]: begin
        reg_rdata_next[31:0] = out6_qs;
      end

      addr_hit[18]: begin
        reg_rdata_next[31:0] = out7_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module radix8_butterfly_reg_top_intf
#(
  parameter int AW = 7,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output radix8_butterfly_reg_pkg::radix8_butterfly_reg2hw_t reg2hw, // Write
  input  radix8_butterfly_reg_pkg::radix8_butterfly_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  radix8_butterfly_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


