// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package simple_butterfly_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 5;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [10:0] q;
  } simple_butterfly_reg2hw_twiddle_reg_t;

  typedef struct packed {
    logic [23:0] q;
  } simple_butterfly_reg2hw_op_left_reg_t;

  typedef struct packed {
    logic [23:0] q;
    logic        qe;
  } simple_butterfly_reg2hw_op_right_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } simple_butterfly_hw2reg_status_reg_t;

  typedef struct packed {
    logic [23:0] d;
    logic        de;
  } simple_butterfly_hw2reg_result_left_reg_t;

  typedef struct packed {
    logic [23:0] d;
    logic        de;
  } simple_butterfly_hw2reg_result_right_reg_t;

  // Register -> HW type
  typedef struct packed {
    simple_butterfly_reg2hw_twiddle_reg_t twiddle; // [59:49]
    simple_butterfly_reg2hw_op_left_reg_t op_left; // [48:25]
    simple_butterfly_reg2hw_op_right_reg_t op_right; // [24:0]
  } simple_butterfly_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    simple_butterfly_hw2reg_status_reg_t status; // [51:50]
    simple_butterfly_hw2reg_result_left_reg_t result_left; // [49:25]
    simple_butterfly_hw2reg_result_right_reg_t result_right; // [24:0]
  } simple_butterfly_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] SIMPLE_BUTTERFLY_TWIDDLE_OFFSET = 5'h 0;
  parameter logic [BlockAw-1:0] SIMPLE_BUTTERFLY_OP_LEFT_OFFSET = 5'h 4;
  parameter logic [BlockAw-1:0] SIMPLE_BUTTERFLY_OP_RIGHT_OFFSET = 5'h 8;
  parameter logic [BlockAw-1:0] SIMPLE_BUTTERFLY_STATUS_OFFSET = 5'h c;
  parameter logic [BlockAw-1:0] SIMPLE_BUTTERFLY_RESULT_LEFT_OFFSET = 5'h 10;
  parameter logic [BlockAw-1:0] SIMPLE_BUTTERFLY_RESULT_RIGHT_OFFSET = 5'h 14;

  // Register index
  typedef enum int {
    SIMPLE_BUTTERFLY_TWIDDLE,
    SIMPLE_BUTTERFLY_OP_LEFT,
    SIMPLE_BUTTERFLY_OP_RIGHT,
    SIMPLE_BUTTERFLY_STATUS,
    SIMPLE_BUTTERFLY_RESULT_LEFT,
    SIMPLE_BUTTERFLY_RESULT_RIGHT
  } simple_butterfly_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] SIMPLE_BUTTERFLY_PERMIT [6] = '{
    4'b 0011, // index[0] SIMPLE_BUTTERFLY_TWIDDLE
    4'b 0111, // index[1] SIMPLE_BUTTERFLY_OP_LEFT
    4'b 0111, // index[2] SIMPLE_BUTTERFLY_OP_RIGHT
    4'b 0001, // index[3] SIMPLE_BUTTERFLY_STATUS
    4'b 0111, // index[4] SIMPLE_BUTTERFLY_RESULT_LEFT
    4'b 0111  // index[5] SIMPLE_BUTTERFLY_RESULT_RIGHT
  };

endpackage

