PULP_APP = main
# REMOVED: PULP_APP_FC_SRCS = main.c
# ADDED: Run on the Cluster to access the DMA!
PULP_APP_CL_SRCS = main.c  
PULP_APP_HOST_SRCS = main.c
PULP_CFLAGS = -O3 -g

include $(PULP_SDK_HOME)/install/rules/pulp_rt.mk
