// =============================================================================
// hermitian_mf_chain.sv
// -----------------------------------------------------------------------------
// Integration module: Hermitian Transpose → Matched Filter chain.
//
// Computes:   g = H^H · y
//
//   H      : ROWS × COLS  (input channel matrix)
//   H^H    : COLS × ROWS  (Hermitian transpose; generated by hermitian_pipe)
//   y      : COLS × 1     (received vector; HH_COLS elements)
//   g      : ROWS × 1     (matched-filter output; HH_ROWS elements)
//
// Dimensional mapping (TASK 3)
// -----------------------------
//   hermitian_pipe output:    hh_real/imag [0:COLS-1][0:ROWS-1]
//   ref_matched_filter_pipe:  hh_real/imag [0:HH_ROWS-1][0:HH_COLS-1]
//
//   Therefore:  HH_ROWS = COLS   (rows of H^H = cols of H)
//               HH_COLS = ROWS   (cols of H^H = rows of H, dot-product length K)
//
//   The hermitian_pipe output is wired DIRECTLY to the MF hh_real/imag ports —
//   no transposition adapter is required because both arrays share the same
//   packed dimension order [0:HH_ROWS-1][0:HH_COLS-1] = [0:COLS-1][0:ROWS-1].
//
// Ownership model (per architectural specification)
// --------------------------------------------------
//   hermitian_pipe  : coefficient GENERATION (no storage)
//   ref_matched_filter_pipe : coefficient STORAGE (coef_real, coef_imag)
//   hh_load         : driven by hermitian_pipe.valid_out
//
// Pipeline latency
// ----------------
//   hermitian_pipe  : REGISTER_OUTPUT=1  →  1 cycle
//   matched_filter  : 1 + $clog2(HH_COLS) = 1 + $clog2(ROWS)
//                     For ROWS=8: 1+3 = 4 cycles
//   TOTAL           : HERM_LAT + MF_LAT  (5 cycles for 8×8 default)
//
// Throughput
// ----------
//   Both sub-blocks have II=1.  This chain has II=1.
//   One output vector per cycle after pipeline fill.
//
// Coefficient reload model (MODE A)
// -----------------------------------
//   1. Assert h_valid_in with H matrix on input.
//   2. hermitian_pipe computes H^H and asserts valid_out one cycle later.
//   3. valid_out is used as hh_load — the MF latches all coefficients.
//   4. Stream y vectors through MF; g = H^H · y emerges TOTAL_LATENCY after
//      the first y valid_in.
//   5. To switch channel matrix: pulse h_valid_in again with the new H;
//      hh_load fires automatically one cycle later, overwriting coef registers.
//
// =============================================================================

module hermitian_mf_chain #(

    // -------------------------------------------------------------------------
    // H matrix dimensions
    //   H  :  ROWS × COLS
    //   H^H:  COLS × ROWS  (HH_ROWS = COLS, HH_COLS = ROWS)
    //   HH_COLS must be a power of two (MF adder-tree constraint).
    // -------------------------------------------------------------------------
    parameter int ROWS              = 8,    // rows of H    = HH_COLS (dot-product K)
    parameter int COLS              = 8,    // cols of H    = HH_ROWS (output length)

    // -------------------------------------------------------------------------
    // Fixed-point format (shared between Hermitian and MF coefficient inputs)
    //   Default: Q0.11 → 12-bit signed, 0 integer bits, 11 fractional bits
    // -------------------------------------------------------------------------
    parameter int WL_IN             = 12,
    parameter int INT_BITS_IN       =  0,
    parameter int FRAC_BITS_IN      = 11,

    // -------------------------------------------------------------------------
    // MF internal widened format (before multiply)
    //   Default: Q0.15 → 16-bit signed, 0 integer bits, 15 fractional bits
    // -------------------------------------------------------------------------
    parameter int MF_INTERNAL_WL         = 16,
    parameter int MF_INTERNAL_INT_BITS   =  0,
    parameter int MF_INTERNAL_FRAC_BITS  = 15,

    // -------------------------------------------------------------------------
    // MF output format (post-rounding, after adder tree)
    //   Default: Q4.11 → 16-bit signed, 4 integer bits, 11 fractional bits
    // -------------------------------------------------------------------------
    parameter int MF_WL_OUT         = 16,
    parameter int MF_INT_BITS_OUT   =  4,
    parameter int MF_FRAC_BITS_OUT  = 11

)(
    // -------------------------------------------------------------------------
    // Clock / Reset / Enable
    // -------------------------------------------------------------------------
    input  logic clk,
    input  logic rst_n,
    input  logic en,             // MF pipeline enable (stalls MF stages when low)
                                 // hermitian_pipe has no enable; see note below.

    // -------------------------------------------------------------------------
    // H matrix input (to Hermitian block)
    //   Shape: [0:ROWS-1][0:COLS-1]
    // -------------------------------------------------------------------------
    input  logic                     h_valid_in,
    input  logic signed [WL_IN-1:0] h_real [0:ROWS-1][0:COLS-1],
    input  logic signed [WL_IN-1:0] h_imag [0:ROWS-1][0:COLS-1],

    // -------------------------------------------------------------------------
    // y vector input (to MF)
    //   Shape: [0:ROWS-1]  (HH_COLS = ROWS elements)
    // -------------------------------------------------------------------------
    input  logic                     y_valid_in,
    input  logic signed [WL_IN-1:0] y_real [0:ROWS-1],
    input  logic signed [WL_IN-1:0] y_imag [0:ROWS-1],

    // -------------------------------------------------------------------------
    // g vector output (from MF)
    //   Shape: [0:COLS-1]  (HH_ROWS = COLS elements)
    // -------------------------------------------------------------------------
    output logic                      g_valid_out,
    output logic                      gy_enable,
    output logic signed [MF_WL_OUT-1:0] yhat_real [0:COLS-1],
    output logic signed [MF_WL_OUT-1:0] yhat_imag [0:COLS-1],

    // -------------------------------------------------------------------------
    // Observation ports (available for testbench probing / chaining)
    // -------------------------------------------------------------------------
    output logic hh_load_out,   // pulse that loaded MF coefficients (= herm valid_out)
    output logic signed [WL_IN-1:0] hh_real_obs [0:COLS-1][0:ROWS-1],
    output logic signed [WL_IN-1:0] hh_imag_obs [0:COLS-1][0:ROWS-1]
);

// =============================================================================
// Derived / local parameters
// =============================================================================

    // H^H matrix dimensions consumed by the MF
    localparam int HH_ROWS = COLS;   // rows of H^H    = cols of H
    localparam int HH_COLS = ROWS;   // cols of H^H    = rows of H  (must be PoT)

    // Expose latencies for TB hierarchical reference
    // hermitian_pipe LATENCY localparam is accessible as u_herm.LATENCY
    // ref_matched_filter_pipe LATENCY is accessible as u_mf.LATENCY

// =============================================================================
// Elaboration-time sanity checks
// =============================================================================

`ifdef SIMULATION
    initial begin : chain_param_check
        // WL consistency
        if (WL_IN != 1 + INT_BITS_IN + FRAC_BITS_IN)
            $fatal(1, "hermitian_mf_chain: WL_IN=%0d != 1+%0d+%0d",
                   WL_IN, INT_BITS_IN, FRAC_BITS_IN);
        if (MF_INTERNAL_WL != 1 + MF_INTERNAL_INT_BITS + MF_INTERNAL_FRAC_BITS)
            $fatal(1, "hermitian_mf_chain: MF_INTERNAL_WL mismatch");
        if (MF_WL_OUT != 1 + MF_INT_BITS_OUT + MF_FRAC_BITS_OUT)
            $fatal(1, "hermitian_mf_chain: MF_WL_OUT mismatch");
        // HH_COLS power-of-two check (required by MF adder tree)
        if ((HH_COLS & (HH_COLS - 1)) != 0)
            $fatal(1, "hermitian_mf_chain: HH_COLS=%0d (=ROWS) must be a power of two", HH_COLS);
        // Dimension positivity
        if (ROWS < 1) $fatal(1, "hermitian_mf_chain: ROWS must be >= 1");
        if (COLS < 1) $fatal(1, "hermitian_mf_chain: COLS must be >= 1");

        $display("[hermitian_mf_chain] ROWS=%0d COLS=%0d HH_ROWS=%0d HH_COLS=%0d",
                 ROWS, COLS, HH_ROWS, HH_COLS);
    end
`endif

// =============================================================================
// Internal wire: H^H matrix (Hermitian output → MF coefficient input)
//   Shape: [0:COLS-1][0:ROWS-1]  =  [0:HH_ROWS-1][0:HH_COLS-1]
//   This is a DIRECT connection; no transposition or renaming needed.
// =============================================================================

    logic signed [WL_IN-1:0] hh_real_w [0:HH_ROWS-1][0:HH_COLS-1];
    logic signed [WL_IN-1:0] hh_imag_w [0:HH_ROWS-1][0:HH_COLS-1];

    // hh_load internal signal: sourced from hermitian valid_out
    logic hh_load_int;

// =============================================================================
// Sub-block 1: hermitian_pipe
// -----------------------------------------------------------------------------
// Computes H^H = conj(H)^T.
// REGISTER_OUTPUT=1 → 1-cycle latency, valid_out one cycle after h_valid_in.
// valid_out is wired to hh_load (coefficient ownership per spec).
// No coefficient storage inside hermitian_pipe.
// =============================================================================

    hermitian_pipe #(
        .ROWS             ( ROWS          ),
        .COLS             ( COLS          ),
        .WL               ( WL_IN         ),
        .INT_BITS         ( INT_BITS_IN   ),
        .FRAC_BITS        ( FRAC_BITS_IN  ),
        .REGISTER_OUTPUT  ( 1             )   // 1-cycle latency
    ) u_herm (
        .clk        ( clk         ),
        .rst_n      ( rst_n       ),
        .valid_in   ( h_valid_in  ),
        .h_real     ( h_real      ),
        .h_imag     ( h_imag      ),
        .valid_out  ( hh_load_int ),    // ← drives hh_load into MF
        .hh_real    ( hh_real_w   ),    // [0:COLS-1][0:ROWS-1] = [0:HH_ROWS-1][0:HH_COLS-1]
        .hh_imag    ( hh_imag_w   )
    );

// =============================================================================
// Sub-block 2: ref_matched_filter_pipe
// -----------------------------------------------------------------------------
// Computes g = H^H · y.
// Coefficient storage (coef_real, coef_imag) lives here, loaded by hh_load.
// Latency: 1 + $clog2(HH_COLS) cycles (4 cycles for HH_COLS=8).
// hh_load is sourced from hermitian_pipe.valid_out (ownership model compliant).
//
// NOTE on en vs hh_load:
//   hh_load is not gated by en (MF design intention).
//   Coefficients can be refreshed during a pipeline stall with no loss.
// =============================================================================

    ref_matched_filter_pipe #(
        .HH_ROWS               ( HH_ROWS              ),
        .HH_COLS               ( HH_COLS              ),
        .MF_WL_IN              ( WL_IN                ),
        .MF_INT_BITS_IN        ( INT_BITS_IN          ),
        .MF_FRAC_BITS_IN       ( FRAC_BITS_IN         ),
        .MF_INTERNAL_WL        ( MF_INTERNAL_WL       ),
        .MF_INTERNAL_INT_BITS  ( MF_INTERNAL_INT_BITS ),
        .MF_INTERNAL_FRAC_BITS ( MF_INTERNAL_FRAC_BITS),
        .MF_WL_OUT             ( MF_WL_OUT            ),
        .MF_INT_BITS_OUT       ( MF_INT_BITS_OUT      ),
        .MF_FRAC_BITS_OUT      ( MF_FRAC_BITS_OUT     )
    ) u_mf (
        .clk        ( clk         ),
        .rst_n      ( rst_n       ),
        .en         ( en          ),
        // --- Coefficient load (driven by Hermitian, not by top-level user) ---
        .hh_load    ( hh_load_int ),    // hermitian valid_out → MF coefficient latch
        .hh_real    ( hh_real_w   ),    // H^H real: [HH_ROWS][HH_COLS]
        .hh_imag    ( hh_imag_w   ),    // H^H imag: [HH_ROWS][HH_COLS]
        // --- Streaming y vector ---
        .valid_in   ( y_valid_in  ),
        .y_real     ( y_real      ),    // [0:ROWS-1] = [0:HH_COLS-1]
        .y_imag     ( y_imag      ),
        // --- Filtered output ---
        .valid_out  ( g_valid_out ),
        .gy_enable  ( gy_enable   ),
        .yhat_real  ( yhat_real      ),    // [0:COLS-1] = [0:HH_ROWS-1]
        .yhat_imag  ( yhat_imag      )
    );

// =============================================================================
// Observation port assignments
// =============================================================================

    assign hh_load_out  = hh_load_int;

    // Expose H^H wires for TB probing (coefficient ownership verification)
    generate
        for (genvar gr = 0; gr < HH_ROWS; gr++) begin : g_obs_row
            for (genvar gc = 0; gc < HH_COLS; gc++) begin : g_obs_col
                assign hh_real_obs[gr][gc] = hh_real_w[gr][gc];
                assign hh_imag_obs[gr][gc] = hh_imag_w[gr][gc];
            end
        end
    endgenerate

endmodule