// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`


`include "common_cells/assertions.svh"

module butterfly_reg_top #(
  parameter type reg_req_t = logic,
  parameter type reg_rsp_t = logic,
  parameter int AW = 5
) (
  input logic clk_i,
  input logic rst_ni,
  input  reg_req_t reg_req_i,
  output reg_rsp_t reg_rsp_o,
  // To HW
  output butterfly_reg_pkg::butterfly_reg2hw_t reg2hw, // Write
  input  butterfly_reg_pkg::butterfly_hw2reg_t hw2reg, // Read


  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import butterfly_reg_pkg::* ;

  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [BlockAw-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;

  // Below register interface can be changed
  reg_req_t  reg_intf_req;
  reg_rsp_t  reg_intf_rsp;


  assign reg_intf_req = reg_req_i;
  assign reg_rsp_o = reg_intf_rsp;


  assign reg_we = reg_intf_req.valid & reg_intf_req.write;
  assign reg_re = reg_intf_req.valid & ~reg_intf_req.write;
  assign reg_addr = reg_intf_req.addr[BlockAw-1:0];
  assign reg_wdata = reg_intf_req.wdata;
  assign reg_be = reg_intf_req.wstrb;
  assign reg_intf_rsp.rdata = reg_rdata;
  assign reg_intf_rsp.error = reg_error;
  assign reg_intf_rsp.ready = 1'b1;

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err;


  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic ctrl_trigger_wd;
  logic ctrl_trigger_we;
  logic ctrl_clear_wd;
  logic ctrl_clear_we;
  logic status_qs;
  logic status_re;
  logic [10:0] twiddle_qs;
  logic [10:0] twiddle_wd;
  logic twiddle_we;
  logic [23:0] op_left_qs;
  logic [23:0] op_left_wd;
  logic op_left_we;
  logic [23:0] op_right_qs;
  logic [23:0] op_right_wd;
  logic op_right_we;
  logic [23:0] res_left_qs;
  logic res_left_re;
  logic [23:0] res_right_qs;
  logic res_right_re;

  // Register instances
  // R[ctrl]: V(True)

  //   F[trigger]: 0:0
  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl_trigger (
    .re     (1'b0),
    .we     (ctrl_trigger_we),
    .wd     (ctrl_trigger_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.ctrl.trigger.qe),
    .q      (reg2hw.ctrl.trigger.q ),
    .qs     ()
  );


  //   F[clear]: 1:1
  prim_subreg_ext #(
    .DW    (1)
  ) u_ctrl_clear (
    .re     (1'b0),
    .we     (ctrl_clear_we),
    .wd     (ctrl_clear_wd),
    .d      ('0),
    .qre    (),
    .qe     (reg2hw.ctrl.clear.qe),
    .q      (reg2hw.ctrl.clear.q ),
    .qs     ()
  );


  // R[status]: V(True)

  prim_subreg_ext #(
    .DW    (1)
  ) u_status (
    .re     (status_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.status.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (status_qs)
  );


  // R[twiddle]: V(False)

  prim_subreg #(
    .DW      (11),
    .SWACCESS("RW"),
    .RESVAL  (11'h0)
  ) u_twiddle (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (twiddle_we),
    .wd     (twiddle_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.twiddle.q ),

    // to register interface (read)
    .qs     (twiddle_qs)
  );


  // R[op_left]: V(False)

  prim_subreg #(
    .DW      (24),
    .SWACCESS("RW"),
    .RESVAL  (24'h0)
  ) u_op_left (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (op_left_we),
    .wd     (op_left_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.op_left.q ),

    // to register interface (read)
    .qs     (op_left_qs)
  );


  // R[op_right]: V(False)

  prim_subreg #(
    .DW      (24),
    .SWACCESS("RW"),
    .RESVAL  (24'h0)
  ) u_op_right (
    .clk_i   (clk_i    ),
    .rst_ni  (rst_ni  ),

    // from register interface
    .we     (op_right_we),
    .wd     (op_right_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0  ),

    // to internal hardware
    .qe     (reg2hw.op_right.qe),
    .q      (reg2hw.op_right.q ),

    // to register interface (read)
    .qs     (op_right_qs)
  );


  // R[res_left]: V(True)

  prim_subreg_ext #(
    .DW    (24)
  ) u_res_left (
    .re     (res_left_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.res_left.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (res_left_qs)
  );


  // R[res_right]: V(True)

  prim_subreg_ext #(
    .DW    (24)
  ) u_res_right (
    .re     (res_right_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.res_right.d),
    .qre    (),
    .qe     (),
    .q      (),
    .qs     (res_right_qs)
  );




  logic [6:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[0] = (reg_addr == BUTTERFLY_CTRL_OFFSET);
    addr_hit[1] = (reg_addr == BUTTERFLY_STATUS_OFFSET);
    addr_hit[2] = (reg_addr == BUTTERFLY_TWIDDLE_OFFSET);
    addr_hit[3] = (reg_addr == BUTTERFLY_OP_LEFT_OFFSET);
    addr_hit[4] = (reg_addr == BUTTERFLY_OP_RIGHT_OFFSET);
    addr_hit[5] = (reg_addr == BUTTERFLY_RES_LEFT_OFFSET);
    addr_hit[6] = (reg_addr == BUTTERFLY_RES_RIGHT_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[0] & (|(BUTTERFLY_PERMIT[0] & ~reg_be))) |
               (addr_hit[1] & (|(BUTTERFLY_PERMIT[1] & ~reg_be))) |
               (addr_hit[2] & (|(BUTTERFLY_PERMIT[2] & ~reg_be))) |
               (addr_hit[3] & (|(BUTTERFLY_PERMIT[3] & ~reg_be))) |
               (addr_hit[4] & (|(BUTTERFLY_PERMIT[4] & ~reg_be))) |
               (addr_hit[5] & (|(BUTTERFLY_PERMIT[5] & ~reg_be))) |
               (addr_hit[6] & (|(BUTTERFLY_PERMIT[6] & ~reg_be)))));
  end

  assign ctrl_trigger_we = addr_hit[0] & reg_we & !reg_error;
  assign ctrl_trigger_wd = reg_wdata[0];

  assign ctrl_clear_we = addr_hit[0] & reg_we & !reg_error;
  assign ctrl_clear_wd = reg_wdata[1];

  assign status_re = addr_hit[1] & reg_re & !reg_error;

  assign twiddle_we = addr_hit[2] & reg_we & !reg_error;
  assign twiddle_wd = reg_wdata[10:0];

  assign op_left_we = addr_hit[3] & reg_we & !reg_error;
  assign op_left_wd = reg_wdata[23:0];

  assign op_right_we = addr_hit[4] & reg_we & !reg_error;
  assign op_right_wd = reg_wdata[23:0];

  assign res_left_re = addr_hit[5] & reg_re & !reg_error;

  assign res_right_re = addr_hit[6] & reg_re & !reg_error;

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[0] = '0;
        reg_rdata_next[1] = '0;
      end

      addr_hit[1]: begin
        reg_rdata_next[0] = status_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[10:0] = twiddle_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[23:0] = op_left_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[23:0] = op_right_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[23:0] = res_left_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[23:0] = res_right_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit))

endmodule

module butterfly_reg_top_intf
#(
  parameter int AW = 5,
  localparam int DW = 32
) (
  input logic clk_i,
  input logic rst_ni,
  REG_BUS.in  regbus_slave,
  // To HW
  output butterfly_reg_pkg::butterfly_reg2hw_t reg2hw, // Write
  input  butterfly_reg_pkg::butterfly_hw2reg_t hw2reg, // Read
  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);
 localparam int unsigned STRB_WIDTH = DW/8;

`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

  // Define structs for reg_bus
  typedef logic [AW-1:0] addr_t;
  typedef logic [DW-1:0] data_t;
  typedef logic [STRB_WIDTH-1:0] strb_t;
  `REG_BUS_TYPEDEF_ALL(reg_bus, addr_t, data_t, strb_t)

  reg_bus_req_t s_reg_req;
  reg_bus_rsp_t s_reg_rsp;
  
  // Assign SV interface to structs
  `REG_BUS_ASSIGN_TO_REQ(s_reg_req, regbus_slave)
  `REG_BUS_ASSIGN_FROM_RSP(regbus_slave, s_reg_rsp)

  

  butterfly_reg_top #(
    .reg_req_t(reg_bus_req_t),
    .reg_rsp_t(reg_bus_rsp_t),
    .AW(AW)
  ) i_regs (
    .clk_i,
    .rst_ni,
    .reg_req_i(s_reg_req),
    .reg_rsp_o(s_reg_rsp),
    .reg2hw, // Write
    .hw2reg, // Read
    .devmode_i
  );
  
endmodule


