`timescale 1ns / 1ps

module tb_fft8;

    // --------------------------------------------------------
    // Parameters & Signals
    // --------------------------------------------------------
    parameter DATA_WIDTH = 12;
    parameter N = 8;                   // 8-point FFT
    parameter NUM_FRAMES = 10000;       // Must match the 'n_seeds' in MATLAB
    parameter TOTAL_SAMPLES = N * NUM_FRAMES;
    localparam CLK_PERIOD = 10;

    reg clk;
    reg rst_n;
    reg valid_in;
    reg signed [DATA_WIDTH-1:0] in_r;
    reg signed [DATA_WIDTH-1:0] in_i;

    wire signed [DATA_WIDTH-1:0] out_r;
    wire signed [DATA_WIDTH-1:0] out_i;
    wire valid_out;
    wire frame_done,out_index;

    // --------------------------------------------------------
    // Memory Arrays for File I/O
    // Size = Total Samples * 2 (because Real and Imag are on separate lines)
    // --------------------------------------------------------
    reg [DATA_WIDTH-1:0] input_mem  [0:(TOTAL_SAMPLES*2)-1];
    reg [DATA_WIDTH-1:0] golden_mem [0:(TOTAL_SAMPLES*2)-1];

    initial begin
        // Load the text files generated by MATLAB into memory
        // Make sure these files are in the same directory as your simulation run folder!
        $readmemb("input_data1.txt", input_mem);
        $readmemb("output_data1.txt", golden_mem);
        $display("Files loaded successfully.");
    end

    // --------------------------------------------------------
    // Instantiate the DUT 
    // --------------------------------------------------------
    fft8_dif #(
        .DATA_WIDTH(DATA_WIDTH)
    ) dut (
        .clk(clk),
        .rst_n(rst_n),
        .valid_in(valid_in),
        .in_r(in_r),
        .in_i(in_i),
        .out_r(out_r),
        .out_i(out_i),
        .valid_out(valid_out),
        .frame_done(frame_done),
        .out_index(out_index)
    );

    // --------------------------------------------------------
    // Clock Generation
    // --------------------------------------------------------
    initial clk = 0;
    always #(CLK_PERIOD/2) clk = ~clk;

    // --------------------------------------------------------
    // 1. DRIVER BLOCK (Feeds inputs into DUT)
    // --------------------------------------------------------
    integer frame, i;
    initial begin
        rst_n = 0;
        valid_in = 0;
        in_r = 0;
        in_i = 0;

        #(CLK_PERIOD * 2);
        rst_n = 1;
        #(CLK_PERIOD * 2);

        $display("Starting to drive %0d frames...", NUM_FRAMES);

        for (frame = 0; frame < NUM_FRAMES; frame = frame + 1) begin
            // Drive 8 points for the current frame
            for (i = 0; i < N; i = i + 1) begin
                @(negedge clk);
                valid_in = 1;
                // Read Real from even index, Imag from odd index
                in_r = input_mem[(frame * N + i) * 2];     
                in_i = input_mem[(frame * N + i) * 2 + 1]; 
            end

            // Pause between frames to let the pipeline drain (Avoids the overwrite bug)
            @(negedge clk);
            valid_in = 0;
            in_r = 0;
            in_i = 0;
            repeat(8) @(negedge clk); 
        end
        $display("All inputs driven. Waiting for outputs to finish...");
    end

// --------------------------------------------------------
    // 2. CHECKER BLOCK (Sequential Read - No Bit Reversal)
    // --------------------------------------------------------
    integer out_count = 0;
    integer pass_count = 0;
    integer fail_count = 0;
    reg signed [DATA_WIDTH-1:0] exp_r, exp_i;

    always @(posedge clk) begin
        if (rst_n && valid_out) begin
            
            // Read sequentially directly from the memory arrays
            exp_r = golden_mem[out_count * 2];
            exp_i = golden_mem[out_count * 2 + 1];

            // Compare
            if (out_r === exp_r && out_i === exp_i) begin
                pass_count = pass_count + 1;
            end else begin
                fail_count = fail_count + 1;
                // Print the first 10 errors
                if (fail_count <= 10) begin
                    $display("MISMATCH at sample %0d (Frame %0d):", out_count%8, (out_count/8)+1);
                    $display("   Expected: R=%b, I=%b", exp_r, exp_i);
                    $display("   Got     : R=%b, I=%b", out_r, out_i);
                end
            end

            out_count = out_count + 1;

            // Check if simulation is completely finished
            if (out_count == TOTAL_SAMPLES) begin
                $display("\n========================================");
                $display("       SIMULATION COMPLETE              ");
                $display("========================================");
                $display(" Total Samples Checked : %0d", out_count);
                $display(" PASSED                : %0d", pass_count);
                $display(" FAILED                : %0d", fail_count);
                $display("========================================");
                if (fail_count == 0)
                    $display(" >> STATUS: PERFECT MATCH! SUCCESS!");
                else
                    $display(" >> STATUS: SIMULATION FAILED.");
                $display("========================================\n");
                $finish;
            end
        end
    end
    // --------------------------------------------------------
    // Watchdog Timer (In case valid_out hangs)
    // --------------------------------------------------------
    initial begin
        // Timeout after giving it plenty of time to process 1000 frames
        #(CLK_PERIOD * 30 * NUM_FRAMES); 
        $display("\n[ERROR] Watchdog Timeout! valid_out stopped firing.");
        $display("Samples checked so far: %0d out of %0d", out_count, TOTAL_SAMPLES);
        $finish;
    end

endmodule