`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

// ==============================================================================
// MODULE: simple_butterfly_top
// PURPOSE: This is the "Protective Wrapper" around your handwritten Butterfly RTL.
//          It exposes a standard AXI slave interface to the PULP SoC Crossbar, 
//          allowing the RISC-V core to communicate with the accelerator using 
//          standard C pointers (Memory-Mapped I/O).
// ==============================================================================
module simple_butterfly_top #(
    // These parameters match the PULP SoC AXI crossbar widths
    parameter int unsigned AXI_ADDR_WIDTH = 32,
    localparam int unsigned AXI_DATA_WIDTH = 32,
    parameter int unsigned AXI_ID_WIDTH = -1,
    parameter int unsigned AXI_USER_WIDTH = -1
)(
    input  logic                clk_i,
    input  logic                rst_ni,
    input  logic                test_mode_i,
    
    // The single front-door connection to the SoC's AXI crossbar
    AXI_BUS.Slave               axi_slave
);

    // --------------------------------------------------------------------------
    // 1. IMPORTING THE AUTOGENERATED TYPES
    // --------------------------------------------------------------------------
    // These structs were generated by `reggen` from your .hjson file.
    // reg2hw: Carries the .q (stable data) and .qe (trigger pulses) to hardware.
    // hw2reg: Carries the .d (results) and .de (write enables) back to software.
    import simple_butterfly_reg_pkg::simple_butterfly_reg2hw_t;
    import simple_butterfly_reg_pkg::simple_butterfly_hw2reg_t;

    // --------------------------------------------------------------------------
    // 2. PROTOCOL DOWNGRADE (AXI -> REG_BUS)
    // --------------------------------------------------------------------------
    // AXI is too complex for simple registers. This internal bus is a simpler 
    // intermediate protocol (just address, data, and valid flags).
    REG_BUS #(.ADDR_WIDTH(32), .DATA_WIDTH(32)) axi_to_regfile();

    // Instantiate the typed structs to hold the hardware wires
    simple_butterfly_reg2hw_t reg_file_to_ip;
    simple_butterfly_hw2reg_t ip_to_reg_file;

    // The actual converter block. It catches AXI transactions from `axi_slave` 
    // and downgrades them into `axi_to_regfile` (REG_BUS) transactions.
    axi_to_reg_intf #(
        .ADDR_WIDTH(AXI_ADDR_WIDTH), .DATA_WIDTH(AXI_DATA_WIDTH),
        .ID_WIDTH(AXI_ID_WIDTH), .USER_WIDTH(AXI_USER_WIDTH), .DECOUPLE_W(0)
    ) i_axi2reg (
        .clk_i(clk_i), .rst_ni(rst_ni), .testmode_i(test_mode_i),
        .in(axi_slave), .reg_o(axi_to_regfile)
    );

    // --------------------------------------------------------------------------
    // 3. INTERFACE-TO-STRUCT ADAPTER MACROS
    // --------------------------------------------------------------------------
    // Auto-generated register files cannot use SystemVerilog Interfaces.
    // They require pure structs. These macros seamlessly map the signals from 
    // the `REG_BUS` interface into the `reg_req_t` and `reg_rsp_t` structs.
    typedef logic [AXI_ADDR_WIDTH-1:0]   addr_t;
    typedef logic [AXI_DATA_WIDTH-1:0]   data_t;
    typedef logic [AXI_DATA_WIDTH/8-1:0] strb_t;

    `REG_BUS_TYPEDEF_REQ(reg_req_t, addr_t, data_t, strb_t)
    `REG_BUS_TYPEDEF_RSP(reg_rsp_t, data_t)

    reg_req_t to_reg_file_req;
    reg_rsp_t from_reg_file_rsp;

    // Connect the interface signals to the struct fields (Zero latency)
    `REG_BUS_ASSIGN_TO_REQ(to_reg_file_req, axi_to_regfile)
    `REG_BUS_ASSIGN_FROM_RSP(axi_to_regfile, from_reg_file_rsp)

    // --------------------------------------------------------------------------
    // 4. THE REGISTER FILE (The Translation Boundary)
    // --------------------------------------------------------------------------
    // This block is auto-generated by `reggen`. 
    // Left side: Takes the struct-based bus requests.
    // Right side: Drives the physical wires (.q, .qe) and reads physical wires (.d).
    simple_butterfly_reg_top #(
        .reg_req_t(reg_req_t), .reg_rsp_t(reg_rsp_t)
    ) i_regfile (
        .clk_i, .rst_ni, .devmode_i(1'b1),
        .reg_req_i(to_reg_file_req), .reg_rsp_o(from_reg_file_rsp),
        .reg2hw(reg_file_to_ip), .hw2reg(ip_to_reg_file)
    );

    // --------------------------------------------------------------------------
    // 5. THE HANDWRITTEN BUTTERFLY RTL (The 7-Cycle Engine)
    // --------------------------------------------------------------------------
    // Internal wires to catch the outputs of the hardware pipeline
    wire signed [23:0] w_o_left;
    wire signed [23:0] w_o_right;
    wire               w_o_aux;

    simple_butterfly #(
        .IWIDTH(12), .CWIDTH(16), .OWIDTH(12), .SHIFT(0) 
    ) i_butterfly (
        .i_clk          (clk_i),
        .i_reset        (~rst_ni),
        .i_clk_enable   (1'b1),
        
        // --- STABLE INPUTS (.q wires) ---
        // These hold their value indefinitely after the C driver writes to them.
        .i_twiddle_idx  (reg_file_to_ip.twiddle.q),
        .i_left         (reg_file_to_ip.op_left.q),
        .i_right        (reg_file_to_ip.op_right.q),
        
        // --- THE ZERO-OVERHEAD TRIGGER (.qe wire) ---
        // Because OP_RIGHT has "hwqe":"true" in the .hjson, this wire pulses HIGH 
        // for exactly one clock cycle the moment the RISC-V core writes the final operand.
        // It immediately drops the hardware into Cycle 1 of its 7-cycle pipeline.
        .i_aux          (reg_file_to_ip.op_right.qe),
        
        // --- HARDWARE OUTPUTS ---
        .o_left         (w_o_left),
        .o_right        (w_o_right),
        .o_aux          (w_o_aux) // Goes high exactly 7 cycles after i_aux pulses
    );

    // --------------------------------------------------------------------------
    // 6. HARDWARE-TO-SOFTWARE WRITE-BACKS (.d and .de mapping)
    // --------------------------------------------------------------------------
    
    // STATUS REGISTER: Auto-clears and auto-sets!
    // If the pipeline finishes (w_o_aux = 1), drive '1'. Otherwise drive '0'.
    assign ip_to_reg_file.status.d  = w_o_aux ? 1'b1 : 1'b0;
    
    // .de is the "Data Enable". It tells the register file WHEN to capture the .d wire.
    // It captures '0' when the trigger (.qe) fires.
    // It captures '1' when the pipeline finishes (w_o_aux).
    assign ip_to_reg_file.status.de = w_o_aux | reg_file_to_ip.op_right.qe;

    // RESULT REGISTERS: Capturing the 7-cycle computation
    // The .d wire is continuously connected to the raw hardware output.
    assign ip_to_reg_file.result_left.d  = w_o_left; 
    // The .de wire pulses HIGH when w_o_aux goes high (after 7 cycles), 
    // safely latching the computed value so the software can read it later.
    assign ip_to_reg_file.result_left.de = w_o_aux; 

    assign ip_to_reg_file.result_right.d  = w_o_right; 
    assign ip_to_reg_file.result_right.de = w_o_aux; 
    
    // =========================================================================
    // 7. HARDWARE DIAGNOSTIC PRINTS (Simulation Only)
    // =========================================================================
    always @(posedge clk_i) begin
        if (reg_file_to_ip.op_right.qe) begin
            $display("[HW DEBUG] CYCLE %0t: Auto-Trigger received on OP_RIGHT! i_aux is HIGH", $time);
            $fflush(); // Force Questasim to print immediately
        end
            
        if (w_o_aux) begin
            // This print will occur exactly 7 cycles after the trigger print
            $display("[HW DEBUG] CYCLE %0t: Pipeline Finished! w_o_aux is HIGH", $time);
            $fflush(); // Force Questasim to print immediately
        end
    end

endmodule
