// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package butterfly_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 5;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [31:0] q;
  } butterfly_reg2hw_coef_reg_t;

  typedef struct packed {
    logic [23:0] q;
  } butterfly_reg2hw_op_left_reg_t;

  typedef struct packed {
    logic [23:0] q;
    logic        qe;
  } butterfly_reg2hw_op_right_reg_t;

  typedef struct packed {
    logic        d;
    logic        de;
  } butterfly_hw2reg_status_reg_t;

  typedef struct packed {
    logic [23:0] d;
    logic        de;
  } butterfly_hw2reg_result_left_reg_t;

  typedef struct packed {
    logic [23:0] d;
    logic        de;
  } butterfly_hw2reg_result_right_reg_t;

  // Register -> HW type
  typedef struct packed {
    butterfly_reg2hw_coef_reg_t coef; // [80:49]
    butterfly_reg2hw_op_left_reg_t op_left; // [48:25]
    butterfly_reg2hw_op_right_reg_t op_right; // [24:0]
  } butterfly_reg2hw_t;

  // HW -> register type
  typedef struct packed {
    butterfly_hw2reg_status_reg_t status; // [51:50]
    butterfly_hw2reg_result_left_reg_t result_left; // [49:25]
    butterfly_hw2reg_result_right_reg_t result_right; // [24:0]
  } butterfly_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] BUTTERFLY_COEF_OFFSET = 5'h 0;
  parameter logic [BlockAw-1:0] BUTTERFLY_OP_LEFT_OFFSET = 5'h 4;
  parameter logic [BlockAw-1:0] BUTTERFLY_OP_RIGHT_OFFSET = 5'h 8;
  parameter logic [BlockAw-1:0] BUTTERFLY_STATUS_OFFSET = 5'h c;
  parameter logic [BlockAw-1:0] BUTTERFLY_RESULT_LEFT_OFFSET = 5'h 10;
  parameter logic [BlockAw-1:0] BUTTERFLY_RESULT_RIGHT_OFFSET = 5'h 14;

  // Register index
  typedef enum int {
    BUTTERFLY_COEF,
    BUTTERFLY_OP_LEFT,
    BUTTERFLY_OP_RIGHT,
    BUTTERFLY_STATUS,
    BUTTERFLY_RESULT_LEFT,
    BUTTERFLY_RESULT_RIGHT
  } butterfly_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] BUTTERFLY_PERMIT [6] = '{
    4'b 1111, // index[0] BUTTERFLY_COEF
    4'b 0111, // index[1] BUTTERFLY_OP_LEFT
    4'b 0111, // index[2] BUTTERFLY_OP_RIGHT
    4'b 0001, // index[3] BUTTERFLY_STATUS
    4'b 0111, // index[4] BUTTERFLY_RESULT_LEFT
    4'b 0111  // index[5] BUTTERFLY_RESULT_RIGHT
  };

endpackage

