`include "register_interface/typedef.svh"
`include "register_interface/assign.svh"

module butterfly_top #(
    parameter int unsigned AXI_ADDR_WIDTH = 32,
    localparam int unsigned AXI_DATA_WIDTH = 32,
    parameter int unsigned AXI_ID_WIDTH = -1,
    parameter int unsigned AXI_USER_WIDTH = -1
)(
    input  logic          clk_i,
    input  logic          rst_ni,
    input  logic          test_mode_i,
    AXI_BUS.Slave         axi_slave
);

    // Import the types autogenerated by reggen
    import butterfly_reg_pkg::butterfly_reg2hw_t;
    import butterfly_reg_pkg::butterfly_hw2reg_t;

    // Declare the internal Register Bus interface
    REG_BUS #(
        .ADDR_WIDTH(32),
        .DATA_WIDTH(32)
    ) axi_to_regfile();

    // =========================================================================
    // STEP 3.5: Declare Register-to-Hardware and Hardware-to-Register Wires
    // =========================================================================
    butterfly_reg2hw_t reg_file_to_ip;  
    butterfly_hw2reg_t ip_to_reg_file;  

    // =========================================================================
    // STEP 3.6: Instantiate the AXI-to-Register Protocol Converter
    // =========================================================================
    axi_to_reg_intf #(
        .ADDR_WIDTH (AXI_ADDR_WIDTH),
        .DATA_WIDTH (AXI_DATA_WIDTH),
        .ID_WIDTH   (AXI_ID_WIDTH),
        .USER_WIDTH (AXI_USER_WIDTH),
        .DECOUPLE_W (0)
    ) i_axi2reg (
        .clk_i      (clk_i),
        .rst_ni     (rst_ni),
        .testmode_i (test_mode_i),
        .in         (axi_slave),      
        .reg_o      (axi_to_regfile)  
    );

    // =========================================================================
    // STEP 3.7: Convert the REG_BUS Interface to Reggen Structs
    // =========================================================================
    typedef logic [AXI_ADDR_WIDTH-1:0]   addr_t;
    typedef logic [AXI_DATA_WIDTH-1:0]   data_t;
    typedef logic [AXI_DATA_WIDTH/8-1:0] strb_t;

    `REG_BUS_TYPEDEF_REQ(reg_req_t, addr_t, data_t, strb_t)
    `REG_BUS_TYPEDEF_RSP(reg_rsp_t, data_t)

    reg_req_t to_reg_file_req;   
    reg_rsp_t from_reg_file_rsp; 

    `REG_BUS_ASSIGN_TO_REQ(to_reg_file_req, axi_to_regfile)
    `REG_BUS_ASSIGN_FROM_RSP(axi_to_regfile, from_reg_file_rsp)

    // =========================================================================
    // STEP 3.8: Instantiate the Autogenerated Register File
    // =========================================================================
    butterfly_reg_top #(
        .reg_req_t(reg_req_t),
        .reg_rsp_t(reg_rsp_t)
    ) i_regfile (
        .clk_i      (clk_i),
        .rst_ni     (rst_ni),
        .devmode_i  (1'b1), 
        
        .reg_req_i  (to_reg_file_req),
        .reg_rsp_o  (from_reg_file_rsp),
        
        .reg2hw     (reg_file_to_ip),
        .hw2reg     (ip_to_reg_file)
    );

    // =========================================================================
    // STEP 3.9: Instantiate and Wire the Butterfly Accelerator
    // =========================================================================
    
    // Intermediate wires for the new 24-bit outputs
    logic [23:0] butterfly_o_left;
    logic [23:0] butterfly_o_right;
    logic        butterfly_o_aux;

    butterfly #(
        .IWIDTH(12),  // Left/Right inputs are 12+12 = 24 bits
        .CWIDTH(16),  // Twiddle is 16+16 = 32 bits
        .OWIDTH(12),  // Outputs are 12+12 = 24 bits
        .SHIFT(0),
        .CKPCE(1)
    ) i_butterfly (
        .i_clk        (clk_i),
        .i_reset      (~rst_ni),
        
        // --- Control Signals ---
        .i_clk_enable (1'b1),
        
        // AUTO-TRIGGER: Fire pipeline when OP_RIGHT is written
        .i_aux        (reg_file_to_ip.op_right.qe),
        
        // --- Input Operands ---
        .i_coef       (reg_file_to_ip.coef.q),        // Removed .val
        .i_left       (reg_file_to_ip.op_left.q),     // Removed .val
        .i_right      (reg_file_to_ip.op_right.q),    // Removed .val
        
        // --- Outputs ---
        .o_left       (butterfly_o_left),
        .o_right      (butterfly_o_right),
        .o_aux        (butterfly_o_aux)
    );

    // =========================================================================
    // STEP 3.10: Output Mapping (Hardware to Registers)
    // =========================================================================
    
    // Status DONE bit
    assign ip_to_reg_file.status.d  = 1'b1;             // Removed .done
    assign ip_to_reg_file.status.de = butterfly_o_aux;  // Removed .done

    // Result Left
    assign ip_to_reg_file.result_left.d  = {8'b0, butterfly_o_left};  // Pad to 32 bits
    assign ip_to_reg_file.result_left.de = butterfly_o_aux;           // Removed .val

    // Result Right
    assign ip_to_reg_file.result_right.d  = {8'b0, butterfly_o_right}; // Pad to 32 bits
    assign ip_to_reg_file.result_right.de = butterfly_o_aux;           // Removed .val
    // =========================================================================
    // Hardware Diagnostic Prints
    // =========================================================================
    always @(posedge clk_i) begin
        if (reg_file_to_ip.op_right.qe)
            $display("[HW DEBUG] CYCLE %0t: Auto-Trigger received on OP_RIGHT! i_aux is HIGH", $time);
            
        if (butterfly_o_aux)
            $display("[HW DEBUG] CYCLE %0t: Pipeline Finished! o_aux is HIGH", $time);
    end

endmodule
